config/routes.rb
Rails.application.routes.draw do
  
  get 'fermos/home'

  get 'fermos/services'

  get 'fermos/about'

  get 'fermos/gallery'

  get 'fermos/reviews'

  get 'fermos/contact'

  root 'fermos#home'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fermos_controller.rb
class FermosController < ApplicationController
  def home
  end

  def services
  end

  def about
  end

  def gallery
  end

  def reviews
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fermos_helper.rb
module FermosHelper
end

app/views/fermos/about.html.erb
<h1>Fermos#about</h1>
<p>Find me in app/views/fermos/about.html.erb</p>

app/views/fermos/contact.html.erb
<h1>Fermos#contact</h1>
<p>Find me in app/views/fermos/contact.html.erb</p>

app/views/fermos/gallery.html.erb
<h1>Fermos#gallery</h1>
<p>Find me in app/views/fermos/gallery.html.erb</p>

app/views/fermos/reviews.html.erb
<h1>Fermos#reviews</h1>
<p>Find me in app/views/fermos/reviews.html.erb</p>

app/views/fermos/services.html.erb
<h1>Fermos#services</h1>
<p>Find me in app/views/fermos/services.html.erb</p>

app/views/layouts/_footer.html.erb
<!-- _________________________ Start Footer _________________________ -->
<footer id="footer" role="contentinfo" class="cmsms_color_scheme_footer cmsms_footer_default">
  <div class="footer_bg">
	<div class="footer_inner">
	  <a href="http://fermos.herokuapp.com/" title="Fermos" class="logo">
	   <img src="http://s7.postimg.org/83yeoztpn/fermos_logo.jpg" alt="Fermos" />
       <img class="footer_logo_retina" src="http://s7.postimg.org/83yeoztpn/fermos_logo.jpg" alt="Fermos" width="165" height="51" />
      </a>
	<div class="cl"></div>
	<nav>
	  <div class="menu-home-garage-container">
	  	<ul id="footer_nav" class="footer_nav">
	  		<li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-10 current_page_item menu-item-1557">
	  			<a href="http://fermos.herokuapp.com">HOME</a>
	  		</li>
            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1476"><a>Services</a>
				<ul class="sub-menu">
					<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1547"><a href="http://garage.cmsmasters.net/about-us/">About Us</a></li>
					<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1562"><a href="http://garage.cmsmasters.net/services-2/">Services</a></li>
					<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1549"><a href="http://garage.cmsmasters.net/our-prices/">Our Prices</a></li>
					<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1550"><a href="http://garage.cmsmasters.net/typography/">Typography</a></li>
				</ul>
            </li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1918"><a href="http://garage.cmsmasters.net/shop/">About</a></li>
<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1477"><a>Gallery</a></li>

<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1447"><a>Reviews</a>
</li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1546">
	<a href="http://garage.cmsmasters.net/contacts-2/">CONTACTS</a></li>
</ul></div></nav><span class="copyright">Fermos © 2015 | All Rights Reserved</span>
			</div>
		</div>
	</footer>
<!-- _________________________ Finish Footer _________________________ -->

app/views/layouts/_header.html.erb
<!-- _________________________ Start Header _________________________ -->
<header id="header">
			<div class="header_top" data-height="35">
			<div class="header_top_outer">
				<div class="header_top_inner">
				<div class="header_top_left"><div class="header_top_aligner"></div><div class="meta_wrap"><div class="meta_wrap_left"><span class="adress cmsms-icon-location-3">Opp Sri Chaitanya Bharati Campus, Ayyappa Society, Hyderabad</span> <span class="phone cmsms-icon-phone-4">+91 70327 23635</span> <a href="#" class="mail cmsms-icon-mail-3">fermos@gmail.com</a></div><div class="meta_wrap_right"><span>Hours:</span><span>Mon-Fri:</span>  8:30am-5:30pm <span>Sat:</span>  9:00am-12:00pm <span>Sun:</span>Closed</div></div></div><div class="cl"></div>
				</div>
			</div>
			<div class="header_top_but closed">
				<span class="cmsms_bot_arrow">
					<span></span>
				</span>
			</div>
		</div>
		<div class="header_mid" data-height="140">
		<div class="header_mid_outer">
			<div class="header_mid_inner">
						
			<div class="logo_wrap">

<a href="http://fermos.herokuapp.com/" title="Garage" class="logo">
	<img src="http://s7.postimg.org/83yeoztpn/fermos_logo.jpg" alt="Garage" />


<img class="logo_retina" src="http://s7.postimg.org/83yeoztpn/fermos_logo.jpg" alt="Garage" width="165" height="51" />
</a>
</div>
			
				<div class="resp_nav_wrap">
					<div class="resp_nav_wrap_inner">
						<div class="resp_nav_content">
							<a class="responsive_nav cmsms_theme_icon_resp_nav" href="javascript:void(0);"></a>
						</div>
					</div>
				</div>
				
<!-- sai nav-->
	<%= render 'layouts/navigation' %>
<!--sai nav close -->
		</div>
	  </div>
	</div>
</header>
<!-- _________________________ Finish Header _________________________ -->

app/views/layouts/_navigation.html.erb
<!-- _________________________ Start Navigation _________________________ -->
<nav role="navigation">
	<div class="menu-home-garage-container">
		<ul id="navigation" class="navigation">
			<li id="menu-item-1557" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-10 current_page_item menu-item-1557 menu-item-depth-0">
				<a href="http://fermos.herokuapp.com"><span class="nav_bg_clr"></span><span>HOME</span></a>
			</li>
			<li id="menu-item-1476" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1476 menu-item-depth-0">
			  <a href="http://fermos.herokuapp.com/fermos/services"><span class="nav_bg_clr"></span><span>Services</span></a>
	          <ul class="sub-menu">
		        <li id="menu-item-1547" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1547 menu-item-depth-1">
		         	<a href="#"><span>About Us</span></a>	
		         </li>
		        <li id="menu-item-1562" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1562 menu-item-depth-1">
		        	<a href="#"><span>Services</span></a>	
		        </li>
		        <li id="menu-item-1549" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1549 menu-item-depth-1">
		        	<a href="#"><span>Our Prices</span></a>	
		        </li>
		        <li id="menu-item-1550" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1550 menu-item-depth-1">
		        	<a href="#"><span>Typography</span></a>	
		        </li>
	          </ul>
	        </li>

		<!-- 	<li id="menu-item-1918" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1918 menu-item-depth-0">
				<a href="#"><span class="nav_bg_clr"></span><span>Gallery</span></a>
			</li> -->

			<li><%= link_to 'Gallery', fermos_gallery_path, id: 'menu-item-1918', class: 'menu-item menu-item-type-post_type menu-item-object-page menu-item-1918 menu-item-depth-0' %></li>

			<li id="menu-item-1477" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1477 menu-item-mega menu-item-mega-cols-four menu-item-depth-0">
				<a href="http://fermos.herokuapp.com/fermos/about"><span class="nav_bg_clr"></span><span>About</span></a>
			</li>

			<li id="menu-item-1447" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1447 menu-item-mega menu-item-mega-cols-five menu-item-depth-0">
				<a href="http://fermos.herokuapp.com/fermos/reviews"><span class="nav_bg_clr"></span><span>Reviews</span></a>
			</li>

			<li id="menu-item-1546" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1546 menu-item-depth-0">
				<a href="http://fermos.herokuapp.com/fermos/contact"><span class="nav_bg_clr"></span><span>CONTACTS</span></a>
			</li>
	    </ul>
	</div>
	<div class="cmsms_dynamic_cart">
		<a href="javascript:void(0);" class="cmsms_dynamic_cart_button cmsms_theme_icon_basket"></a>
		<div class="widget_shopping_cart_content"></div>
	</div>					
	<div class="cl"></div>
</nav>
<!-- _________________________ Finish Navigation _________________________ -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<htmllang="en-US" prefix="og: http://ogp.me/ns#" class="cmsms_html">
<head>
 <title>Fermos Car Service | Hyderabad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<link rel="shortcut icon" href="#" type="image/x-icon" />
<link rel="profile" href="#" />
<link rel="pingback" href="#" />
<!-- This site is optimized with the Yoast WordPress SEO plugin v2.2.1 - https://yoast.com/wordpress/plugins/seo/ -->
<link rel="canonical" href="#" />
<meta property="og:locale" content="en_US" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Home | Fermos" />
<meta property="og:url" content="#" />
<meta property="og:site_name" content="Fermos" />
 <script type='application/ld+json'>
// {"@context":"http:\/\/schema.org","@type":"WebSite","url":"http:\/\/garage.cmsmasters.net\/","name":"Garage","potentialAction":{"@type":"SearchAction","target":"http:\/\/garage.cmsmasters.net\/?s={search_term}","query-input":"required name=search_term"}}
// </script>
<!-- / Yoast WordPress SEO plugin. -->
<link rel="alternate" type="application/rss+xml" title="Fermos &raquo; Feed" href="#" />
<link rel="alternate" type="application/rss+xml" title="Fermos &raquo; Comments Feed" href="#" />
<link rel="alternate" type="text/calendar" title="Fermos &raquo; iCal Feed" href="#" />
<link rel="alternate" type="application/rss+xml" title="Fermos &raquo; Home Comments Feed" href="#" />
<link rel='stylesheet' id='cmsms-google-fonts-css'  href='//fonts.googleapis.com/css?family=Source+Sans+Pro%3A200%2C300%2C400%2C600%2C700%2C900%2C200italic%2C300italic%2C400italic%2C600italic%2C700italic%2C900italic%7CMontserrat+Alternates%3A400%2C700&#038;ver=4.2.2' type='text/css' media='all' />
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/plugins/revslider/rs-plugin/js/jquery.themepunch.tools.min.js?ver=4.6.93'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/plugins/revslider/rs-plugin/js/jquery.themepunch.revolution.min.js?ver=4.6.93'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jsLibraries.min.js?ver=1.0.0'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.iLightBox.min.js?ver=2.2.0'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="#" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="#" /> 
<meta name="generator" content="WordPress 4.2.2" />
<meta name="generator" content="WooCommerce 2.3.11" />
<link rel='shortlink' href='#' />
</head>

<body class="home page page-id-10 page-template-default">

<!-- _________________________ Start Page _________________________ -->
<section id="page" class="chrome_only cmsms_liquid fixed_header enable_header_top hfeed site">

	<!-- _________________________ Start Main _________________________ -->
	<div id="main">
	    <%= render 'layouts/header' %>
	    <%= yield %>
	</div>
	
	<!-- _________________________ Finish Main _________________________ -->
	<%= render 'layouts/footer' %>
</section>
<!-- _________________________ Finish Page _________________________ -->

<link rel='stylesheet' id='cmsms-google-fonts-lemon-css'  href='//fonts.googleapis.com/css?family=Lemon&#038;ver=4.2.2' type='text/css' media='all' />
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-includes/js/comment-reply.min.js?ver=4.2.2'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js?ver=3.51.0-2014.06.20'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/garage.cmsmasters.net\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ..."};
/* ]]> */
</script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=4.2.1'></script>
<script type='text/javascript'>
/* <![CDATA[ */
// var wc_add_to_cart_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","i18n_view_cart":"View Cart","cart_url":"http:\/\/garage.cmsmasters.net\/cart\/","is_cart":"","cart_redirect_after_add":"no"};
/* ]]> */
</script>
<script type='text/javascript' src='//garage.cmsmasters.net/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart.min.js?ver=2.3.11'></script>
<script type='text/javascript' src='//garage.cmsmasters.net/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.60'></script>
<script type='text/javascript'>
/* <![CDATA[ */
// var woocommerce_params = {"ajax_url":"\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script>
<script type='text/javascript' src='//garage.cmsmasters.net/wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min.js?ver=2.3.11'></script>
<script type='text/javascript' src='//garage.cmsmasters.net/wp-content/plugins/woocommerce/assets/js/jquery-cookie/jquery.cookie.min.js?ver=1.4.1'></script>
<script type='text/javascript'>
/* <![CDATA[ */
// var wc_cart_fragments_params = {"ajax_url":"\/wp-admin\/admin-ajax.php","fragment_name":"wc_fragments"};
/* ]]> */
</script>
<script type='text/javascript' src='//garage.cmsmasters.net/wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=2.3.11'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/plugins/cmsms-mega-menu/js/jquery.megaMenu.js?ver=1.2.3'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jqueryLibraries.min.js?ver=1.0.0'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var cmsms_script = {"theme_url":"http:\/\/garage.cmsmasters.net\/wp-content\/themes\/garage","site_url":"http:\/\/garage.cmsmasters.net\/","ilightbox_skin":"dark","ilightbox_path":"vertical","ilightbox_infinite":"0","ilightbox_aspect_ratio":"1","ilightbox_mobile_optimizer":"1","ilightbox_max_scale":"1","ilightbox_min_scale":"0.2","ilightbox_inner_toolbar":"0","ilightbox_smart_recognition":"0","ilightbox_fullscreen_one_slide":"0","ilightbox_fullscreen_viewport":"center","ilightbox_controls_toolbar":"1","ilightbox_controls_arrows":"0","ilightbox_controls_fullscreen":"1","ilightbox_controls_thumbnail":"1","ilightbox_controls_keyboard":"1","ilightbox_controls_mousewheel":"1","ilightbox_controls_swipe":"1","ilightbox_controls_slideshow":"0","ilightbox_close_text":"Close","ilightbox_enter_fullscreen_text":"Enter Fullscreen (Shift+Enter)","ilightbox_exit_fullscreen_text":"Exit Fullscreen (Shift+Enter)","ilightbox_slideshow_text":"Slideshow","ilightbox_next_text":"Next","ilightbox_previous_text":"Previous","ilightbox_load_image_error":"An error occurred when trying to load photo.","ilightbox_load_contents_error":"An error occurred when trying to load contents.","ilightbox_missing_plugin_error":"The content your are attempting to view requires the <a href='{pluginspage}' target='_blank'>{type} plugin<\\\/a>."};
/* ]]> */
</script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.script.js?ver=1.0.0'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.tweet.min.js?ver=1.3.1'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.isotope.min.js?ver=1.5.19'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.isotope.mode.js?ver=1.0.0'></script>
<script type='text/javascript' src='//maps.google.com/maps/api/js?sensor=false&#038;ver=1.0.0'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.gMap.min.js?ver=3.2.0'></script>
<script type='text/javascript' src='http://garage.cmsmasters.net/wp-content/themes/garage/js/jquery.cmsms-woo-script.js?ver=1.0.0'></script>


</body>
</html>